apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-backend
  template:
    metadata:
      labels:
        app: ems-backend
    spec: 
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35  # Lightweight image with simple shell utilities
          command:
            - /bin/sh
            - -c
            - |
              until nc -zv mysql-db 3306; do
                echo "Waiting for MySQL to be ready..."
                sleep 2
              done
              echo "MySQL is ready, proceeding with application startup."
          # Make sure init container finishes before main container starts
          imagePullPolicy: IfNotPresent
      containers:
        - name: java-ems-backend
          image: amanchauhan810/ems-backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ems-java-backend
spec:
  selector:
    app: ems-backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080