apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-frontend
  template:
    metadata:
      labels:
        app: ems-frontend
    spec: 
      containers:
        - name: java-ems-frontend
          image: amanchauhan810/ems-frontend:v2
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: ems-frontend
spec:
  selector:
    app: ems-frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
