apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: demo
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
          - '--storage.tsdb.path=/prometheus'
          - '--config.file=/etc/prometheus/prometheus.yml' # ConfigMap path
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus # Mount the configMap here
          readOnly: true
        - name: prometheus-storage-volume
          mountPath: /prometheus # Persistent storage for Prometheus data
      restartPolicy: Always
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
           # Optional; default permissions for the ConfigMap files
      - name: prometheus-storage-volume
        persistentVolumeClaim:
          claimName: prometheus-pvc
