apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: demo
  labels:
    app: prometheus-deployment
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: prometheus-volume
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: demo
  labels:
    app: prometheus-deployment
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi