apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  local-config.yaml: |
    server:
      http_listen_port: 3100
    ingester:
      wal:
        enabled: true
        dir: /tmp/wal
    storage_config:
      boltdb_shipper:
        directory: /tmp/loki/index
        shared_store: filesystem
      filesystem:
        directory: /tmp/loki/chunks
    limits_config:
      enforce_metric_name: false
    chunk_target_size: 1048576
