apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: nginx:latest
        resources:
          requests:
            memory: 500Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 250m
        ports:
        - containerPort: 80
        
    

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-server
  ports:
  - port: 80
    nodePort: 30123
    targetPort: 80
  type: LoadBalancer