apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 192.168.1.18:5000/test:1.0.0 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 500Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 200m